### PR TITLE
Clear timeout in useEffect

### LINKED ISSUE #173: Bug: Matching Service FE issue - redirect not working as expected
When a user is searching for a match and leaves - after 25 seconds the user still gets redirected to cannot find match page

### PR DESCRIPTION
**Pull request by chunweii**
Fixes #173

### CODE REVIEW

File: frontend/src/pages/interviews/find-match.tsx [hunk 1]
```diff
@@ -15,14 +15,19 @@ export default function FindMatch() {
...
         cancelLooking();
         router.push("/interviews/match-not-found");
       }, 30000);
     }
+    return () => {
+      if (timeout)
+      clearTimeout(timeout);
+    }
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [match, router]);
```
Comment (yhtMinceraft1010X) [inline frontend/src/pages/interviews/find-match.tsx:32]: Should the timeout be part of the dependency array?

**Review by ong6 — APPROVED** [review]
Lgtm
